trigger:
- main
  paths:
    include:
    - application/*
    exclude:
    - infra/*

stages:
- stage: image_build
  displayName: 'Build Docker Image'

  steps:
  - task: DockerCompose@0
    inputs:
      containerregistrytype: 'Azure Container Registry'
      azureSubscription: 'Resource Group Service Connection'
      azureContainerRegistry: '{"loginServer":"calculators.azurecr.io", "id" : "/subscriptions/7122b890-4d38-46fb-8c3d-9e0a76c39cc6/resourceGroups/app_service/providers/Microsoft.ContainerRegistry/registries/calculators"}'
      dockerComposeFile: '**/docker-compose.yml'
      action: 'Build services'

  - stage: deploy_to_staging
    displayName: 'Deploy to staging environment'
    jobs:
    - deployment: 'deploy_to_test'
      environment: 'Staging'
      steps:
      - task: DockerCompose@0
        inputs:
          containerregistrytype: 'Azure Container Registry'
          azureSubscription: 'Resource Group Service Connection'
          azureContainerRegistry: '{"loginServer":"calculators.azurecr.io", "id" : "/subscriptions/7122b890-4d38-46fb-8c3d-9e0a76c39cc6/resourceGroups/app_service/providers/Microsoft.ContainerRegistry/registries/calculators"}'
          dockerComposeFile: '**/docker-compose.yml'
          action: 'Push services'
  
  - stage: deploy_to_production
    displayName: 'Deploy to production environment'
    dependsOn: deploy_to_staging
    jobs:
    - deployment: 'deploy_to_production'
      environment: 'Production'
      steps:
      - task: DockerCompose@0
        inputs:
          containerregistrytype: 'Azure Container Registry'
          azureSubscription: 'Resource Group Service Connection'
          azureContainerRegistry: '{"loginServer":"calculators.azurecr.io", "id" : "/subscriptions/7122b890-4d38-46fb-8c3d-9e0a76c39cc6/resourceGroups/app_service/providers/Microsoft.ContainerRegistry/registries/calculators"}'
          dockerComposeFile: '**/docker-compose.yml'
          action: 'Push services'
