trigger:
  branches:
    include:
      - main  
  paths:
    exclude:
    - infra/* 

variables:
- group: my-calculator-staging
- group: my-calculator-prod

stages:
- stage: docker_image_to_staging
  displayName: 'Build and Push Docker Image to Staging'

  jobs:
  - job: 'to_staging'
    steps:

    - task: AzureKeyVault@2
      inputs:
        azureSubscription: $(azureSubscription-staging)
        KeyVaultName: $(KeyVaultName-staging)
        SecretsFilter: '*'
        RunAsPreJob: false

    - task: DockerCompose@0
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscription: $(azureSubscription-staging)
        azureContainerRegistry: $(azureContainerRegistry)
        dockerComposeFile: '**/docker-compose.yml'
        action: 'Build services'
          
    - task: DockerCompose@0
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscription: $(azureSubscription-staging)
        azureContainerRegistry: $(azureContainerRegistry)
        dockerComposeFile: '**/docker-compose.yml'
        action: 'Push services'


- stage: docker_image_to_production
  displayName: 'Build and Push to production environment'
  dependsOn: docker_image_to_staging

  jobs:
  - job: 'deploy_to_production'
    steps:
    
    - task: AzureKeyVault@2
      inputs:
        azureSubscription: $(azureSubscription-prod)
        KeyVaultName: (KeyVaultName-prod)
        SecretsFilter: '*'
        RunAsPreJob: false

    - task: DockerCompose@0
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscription: $(azureSubscription-prod)
        azureContainerRegistry: $(azureContainerRegistry)
        dockerComposeFile: '**/docker-compose.yml'
        action: 'Build services'

    - task: DockerCompose@0
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscription: $(azureSubscription-prod)
        azureContainerRegistry: $(azureContainerRegistry)
        dockerComposeFile: '**/docker-compose.yml'
        action: 'Push services'
