trigger:
  branches:
    include:
    - main
  paths:
    include:
    - infra/*

variables:
- group: my-calculator-staging
- group: my-calculator-prod

stages:
- stage: app_service_staging
  displayName: 'Create app service for staging'

  jobs:
  - job: staging
    displayName: 'Deploy to staging environment'

    steps:

    - task: AzureKeyVault@2
      inputs:
        azureSubscription: $(azureSubscription-staging)
        KeyVaultName: $(KeyVaultName-staging)
        SecretsFilter: '*'
        RunAsPreJob: false

    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: $(azureSubscription-staging)
        subscriptionId: $(subscriptionId)
        action: 'Create Or Update Resource Group'
        resourceGroupName: $(resourceGroupName)
        location: $(location)
        templateLocation: 'Linked artifact'
        csmFile: $(csmFileTemplate-staging)
        csmParametersFile: $(csmParametersFile-staging)
        overrideParameters: '-subscriptionId $(subscriptionId) -location "$(location)" -hostingPlanName $(hostingPlanName) -serverFarmResourceGroup $(serverFarmResourceGroup) -linuxFxVersion $(linuxFxVersion) -dockerRegistryUrl $(dockerRegistryUrl) -dockerRegistryUsername $(dockerRegistryUsername) -dockerRegistryPassword $(dockerRegistryPassword)'
        deploymentMode: 'Incremental'


- stage: app_service_production
  displayName: 'Create app service for production '
  dependsOn: app_service_staging

  jobs:  
  - job: production
    displayName: 'Deploy to production environment'
    
    steps:

    - task: AzureKeyVault@2
      inputs:
        azureSubscription: $(azureSubscription-prod)
        KeyVaultName: $(KeyVaultName-prod)
        SecretsFilter: '*'
        RunAsPreJob: false

    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: $(azureSubscription-prod)
        subscriptionId: $(subscriptionId)
        action: 'Create Or Update Resource Group'
        resourceGroupName: $(resourceGroupName)
        location: $(location)
        templateLocation: 'Linked artifact'
        csmFile: $(csmFileTemplate-prod)
        csmParametersFile: $(csmParametersFile-prod)
        deploymentMode: 'Incremental'
      