trigger:
  branches:
    include:
    - main
  paths:
    include:
    - infra/*

stages:
- stage: app_service_staging
  displayName: 'Create app service for staging'

  jobs:
  - job: staging
    displayName: 'Deploy to staging environment'

    steps:

    - task: AzureKeyVault@2
      inputs:
        azureSubscription: 'Resource Group fro Staging Env'
        KeyVaultName: 'calculator-staging'
        SecretsFilter: '*'
        RunAsPreJob: false

    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: $(azureResourceManagerConnection)
        subscriptionId: $(subscriptionId)
        action: 'Create Or Update Resource Group'
        resourceGroupName: $(resourceGroupName)
        location: $(location)
        templateLocation: 'Linked artifact'
        csmFile: $(Build.SourcesDirectory)/infra/azuredeploy.json
        csmParametersFile: $(Build.SourcesDirectory)/infra/staging.parameters.json
        deploymentMode: 'Incremental'


- stage: app_service_production
  displayName: 'Create app service for production '
  dependsOn: app_service_staging

  jobs:  
  - job: production
    displayName: 'Deploy to production environment'
    
    steps:

    - task: AzureKeyVault@2
      inputs:
        azureSubscription: 'Resource Group for Prod Env'
        KeyVaultName: 'calculator-prod'
        SecretsFilter: '*'
        RunAsPreJob: false

    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: $(azureResourceManagerConnection)
        subscriptionId: $(subscriptionId)
        action: 'Create Or Update Resource Group'
        resourceGroupName: $(resourceGroupName)
        location: $(location)
        templateLocation: 'Linked artifact'
        csmFile: $(Build.SourcesDirectory)/infra/azuredeploy.json
        csmParametersFile: $(Build.SourcesDirectory)/infra/production.parameters.json
        deploymentMode: 'Incremental'
      